name: todos_data_source_impl
description: An in-memory implementation of the TodosDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  todos_data_source:
    path: ../todos_data_source
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.12
  very_good_analysis: ^6.0.0
